development: &default
  adapter: postgresql
  database: cul-de-sac-development_development
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: cul-de-sac-development_test
